language: ruby
rvm:
- 2.3.3
cache: bundler
before_install:
- chmod +x build.sh
install:
- bundle install
script:
- "./build.sh"
branches:
  only:
  - dev
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: dZNRUE6GCzCEU4RTQDhRiR9xdzJ1OUYrulKbXqz3CUi6pGozKvE4U6fL3wqPSWzyxPb+0GlLE8gQfQgrZZzigCOy5p6hSJdeS2LYSnxtmF1+yg3CUrx2rLctL4K9aJmYkezYgXCbV/HNaIyscKqYGCYM3qjJbb9I0/JlAO69xVLAN3APo3XMG9QQBnaoW42ZgAp22R+E6l/TFZ14Fdwj8Cdh1Z7aRAOn2/uom2JqO5HR7Bt0VyJcu91oa30D260ilGQCBcMh98xtb281a2IdWhQ9dgGyDFLnOuJI3LctL7QO4Wpu1s8RF3xBM9A17LMc6dsayaaSpXS6P25HjnzxoTTuFHSXTzU2jwWdWkYdtl+NTp0O+M4Z+eb+bVPkdGTrPg5pYTq/kf7r1tbniCNtA1SP9E1PE6XOWTSTB6iyjmSKk3yJ5KaAJBCm6Wf5/g5WyhNCDU7h7ksSF0symWeI1fOynZGNMiJcz2KrbuqAa0dWdtGK35dKs/cJ3ciz0Fk3KpVdUkKnLJ2lUq026P5SzCqPG28XKNMnuBLyneNdv8OebnhKroa2+8mXde3UNgC+9h4yrjk+CU8kkXMVT7g/qul2ShcrC3Ln0Sb+p+z9aeRYU/lVt2ztoffPkkU32h3yVoaLx0IIEA5ElO/dvHUqANG/gPAVhOjYxiXr0KCcKYU=
sudo: false
